Pylons/webob

- webob/cachecontrol.py
These supports the RFC 5861 extensions to cache control which allow a site to tell a HTTP cache that it's acceptable to serve a stale response while re-validating the currently cached response (``stale-if-revalidate``) and that it's acceptable to serve a stale response if an error occurs (``stale-if-error``). These both take a number of seconds for which it is acceptable to serve a stale response for.
I didn't write any tests because there doesn't seem to be any that exercise all of the various header options, if this needs tests let me know.
> Support stale-while-revalidate and stale-if-error

- webob/dec.py
the tests and code clearly expect (req, app, **kw) and it makes sense that it
would be that way since req is the ephemeral argument and the rest are
defined at setup-time. The documented order before was (app, req, **kw)
which puts the req in-between multiple config arguments in the
signature.
fixes #25, #120
> bring docs up-to-date with actual wsgify signature

- tests/test_response.py
- webob/response.py
Make sure that header names extracted with Response.from_file are `str` instances otherwise most WSGI implementations will reject the response.
Should fix issue https://github.com/Pylons/webob/issues/99
> Native `str` strings from Response.from_file

- docs/news.txt
- tests/test_cookies.py
- tests/test_cookies_bw.py
- tests/test_response.py
- webob/cookies.py
- webob/response.py
This pull request supersedes the one in https://github.com/Pylons/webob/pull/172
> Fix.cookie handling

- webob/compat.py
- webob/request.py
This backports a patch to Python's ``cgi.FieldStorage`` from the bug tracker to fix an issue on Python 3.x where a mutlipart message has a leading set of blank lines. I'm not sure if this is something webob wants to do or not, but I ran into this problem when working on [Warehouse](https://github.com/pypa/warehouse).
> Include a patch from CPython's bug tracker to fix cgi.FieldStorage on 3.x

- tests/test_request.py
- webob/request.py
Currently Request.from_file ignore the body of a request if the method
is PATCH. This fixes that by using the dictionary we have to know if a
request might have a body or not.
Same goes for as_bytes().
> request: read body from file if the method is PATCH

- webob/descriptors.py
> Use 'name' parameter for messages instead of 'attr' inside 'deprecated_property'

- tests/test_response.py
- webob/response.py
When assigning the 204 status code to a response object, the `content_type` attribute is still present due to `default_content_type = 'text/html'`.
We encountered problems with this behavior in some response handling code which does not explicitly create a `HTTPNoContent` response object having `empty_body = True` but reuses an existing regular response object.
For example, http unit tests using `WebTest` croak with:
> AssertionError: Content-Type header found in a 204 response, which must not return content.
> -- webtest/lint.py, line 447, in check_content_type
> delete response.content_type if assigning 204 (No Content) to response.status

- docs/news.txt
- tests/test_response.py
- webob/response.py
Response headers should have CRLF line endings the same as Request headers. http://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2
> Use '\r\n' line endings in Response.__str__.

- docs/news.txt
- tests/test_multidict.py
- webob/multidict.py
Calling `request.GET.extend([('foo', 'bar')])`  was not keeping ``environ['QUERY_STRING']`` in sync.  This meant that ``request.url``, ``request.path_qs``, &c. got out of sync too. This fixes that.
----
It also fixes some tests whose brokenness became  apparent after ``GetDict.extend`` was fixed. Issues with existing tests were:
- Some tests were putting non-string values into the GetDict.  GetDict doesn't like this. (You can't encode an integer to utf-8.)
- One test passed `GetDict.extend` an object whose `.items()` method returned a list of strings.  `Extend` (rightfully, I think) assumes that `.items()` returns a sequence of (key, value) pairs.
> GetDict.extend() does not update QUERY_STRING

- tests/test_exc.py
- webob/exc.py
Because multiple base classes share and inherit the same status code, the
values of `webob.exc.status_map` are *not* deterministic at import time.  For
example, for any given Python process, `webob.exc.status_map[500]` might
be equal to any of the following:
* WSGIHTTPException
* HTTPServerError
* HTTPError
* HTTPInternalServerError
* HTTPRedirection
> Ensure that webob.exc.status_map is deterministic.

- webob/exc.py
- webob/util.py
Hi,
This change handles 308 http code for permanent redirect
Cheers,
> Handle 308 HTTP code for redirect

- tests/test_request.py
- webob/request.py
Avoids `TypeError: must be str, not bytes`.
Needed for 1.4, 1.5 and master branches.
> Handle PATCH missing content type in req.POST.

- tests/test_descriptors.py
- tests/test_exc.py
- webob/descriptors.py
- webob/exc.py
This adds a sort of seatbelt that makes sure that applications using WebOb are less likely to be vulnerable to HTTP response splitting. Unfortunately due to the flexibility of WebOb it is difficult to guarantee that you can't add a header that is vulnerable, but this adds one more line of defense.
Closes #217
> Add extra security checks for Headers

- tests/test_exc.py
- webob/exc.py
> Add ability to return a JSON body from an exception

- tests/test_response.py
- webob/response.py
Fixes #196. If a charset is already specified in the content-type, I opted to leave it there. Else, no charset will be added to the content-type line when the the effective content-type is JSON.
I also reworked the content-type-checking condition make it more legible.
> Don't add a charset if none is specified and the content-type is JSON.

- tests/test_acceptparse.py
- tests/test_request.py
- webob/acceptparse.py
Primary motivation is to address https://github.com/Pylons/pyramid/issues/1407, which would enable usage of wildcards as an accept predicate:
```python
@view_config(accept='text/*')
def view(request):
...
```
`Webob.acceptparse.MIMEAccept` now supports the following, where previously an exception was raised:
```python
>>> accept = MIMEAccept('text/html')
>>> 'text/*' in accept
True
>>> '*/html' in accept
True
>>> '*' in accept
True
```
- Fixes #155
- Addresses https://github.com/Pylons/pyramid/issues/1407
> Allow wildcards to be used when comparing a MIMEAccept against an offer

- tests/test_request.py
- webob/request.py
* Uses the correct body to be consumed by Trasncode.
* Adds regression test.
* This fixes #76.
> Fix Request.decode that tries to read from an already consumed stream

- tests/test_exc.py
- webob/exc.py
Currently WSGIHTTPException, when served as responses, call _make_body to prepare their body.
_make_body gets each entry of the environ and escapes it at https://github.com/Pylons/webob/blob/master/webob/exc.py#L292 if the user stored any property into a previously used request it will end up being in the environ and so will be escaped.
The side effect is that if the user stored any property which the conversion to string fails, the Response will crash even though that property is not used at all.
This is especially true in case you stored your user inside the request (like repoze.who does), the user is an SQLAlchemy model and you rollback the transaction before performing a redirect.
As redirections are subclasses of _HTTPMove (which provides a custom template) the _make_body will …
> Avoid escaping environ keys that are not used by WSGIHTTPException body_template

- docs/reference.txt
This way Pyramid document can correctly cross reference.
> Adding explicit Sphinx reference to request and response documentation

- tests/test_response.py
- webob/response.py
This is a result of the discussion in [https://github.com/Pylons/pyramid/issues/2625](Pyramid issue 2625).
Purpose of this property is to allow users to check if the `Response` has a body without forcing an evaulation of the underlying `app_iter`. This is handy if you wan't to create a streaming response where the `app_iter` itself is lazy (i.e. streams data over a socket) or the `app_iter` can only read once.
It's pretty much the same code as @bertjwregeer suggested but I added it as property rather than es method because I figured that it's fits better in the overall class design this way. The relevant changes for Pyramid will be done later.
> Adds Reponse.has_body.

- docs/reference.txt
- docs/whatsnew-1.6.txt
- tests/test_exc.py
- tests/test_request.py
- tests/test_response.py
- webob/exc.py
- webob/response.py
- webob/util.py
- Response.content_type removes charset unless the new content_type is a text like type that has a charset parameter
- Reverted change that was made in #253 whereby Response.charset would not allow the user to set a charset if the content type was JSON. I am not a big fan of trying to stop the user from shooting themselves in the foot, and would rather let them add/remove as needed.
- json.dumps/loads are now always UTF-8. Python returns a string to us, and we can encode it as we see fit.
- `Response.__init__` has been cleaned up to remove a lot of extraneous branch conditions that were only complicating the logic.
> Fix: content_type/charset handling

- docs/differences.txt
- tests/test_response.py
- webob/response.py
For example, such as generate the Apple's Passbook.
```python
>>> writer = zipfile.ZipFile(ResponseBodyFile(Response()), 'w')
>>> writer.writestr('zinfo_or_arcname', b'foo')
>>> writer.close()
```
Thanks.
> Support Response.body_file.tell() method for ZipFile friendly

- webob/exc.py
Capturing the function, and returning a new object from a class that is
defined within the capturing function seems to cause some sort of really
pathological behavior that causes lazify() to take up a bunch of CPU
time, especially when it is part of a hot code path.
Thanks to Martijn Faassen (@faassen) for reporting! 
Closes #282
> Move the _lazified class out of the lazify function

- tests/test_request.py
- tests/test_request_nose.py
- webob/request.py
This removes the implicit support of Chunked Encoding within WebOb. WebOb now treats all Requests as body-less unless the Content-Length header is set. This also means that every single HTTP verb (and unknown ones if you'd like :-P) are now allowed to have a body on it, and using wsgiref no longer hangs on non-existent bodies.
```
from wsgiref.simple_server import make_server
from webob import Request, Response
class MyApp(object):
def __call__(self, environ, start_response):
request = Request(environ)
response = Response()
print(request.method)
print(request.body)
response.body = b'Received: ' + request.body
return response(environ, start_response)
httpd = make_server('localhost', 8080, MyApp())
try:
httpd.serve_forever()
except KeyboardInterrupt:
print('^C')
```
test with:
```
curl -X …
```
> Fix: bodies on everything

- tests/test_response.py
- webob/response.py
Pyramid uses `.text` in it's renderers, however with the changes made to remove charset when there is no charset on the content-type, this meant that things would break.
Instead add a new `default_body_encoding` to `Response` that may be used as the alternative to charset. This will allow `.text` to continue functioning.
It's a small backwards incompatible change, but if you were relying on WebOb to complain about no charset being set when accessing `.text` I'd love to have a word with you :-).
Closes #271
> Feature: default body encoding

- tests/test_request.py
- tests/test_response.py
- webob/descriptors.py
- webob/headers.py
- webob/response.py
Based on comments made in #285 I took a look at seeing what could be done to get some of the speed back in the synthetic test that `howareyou` provides.
In that ticket there is a patchset that brings it back to within 2k rps in the benchmark. However the maintenance burden goes up drastically, and I don't think the additional burden is worth the cost.
The new and updated `Response.__init__` is more correct, and has more code re-use by calling various properties/functions rather than trying to do it all. There is a sacrifice, but ultimately WebOb and it's `Response` object are not going to be the bottleneck, especially because outside of the synthetic test that attempts to return a `Response` object as fast as possible user code is going to dominate in cases where WebOb is used.
---- …
> Performance: Response

- .travis.yml
- CHANGES.txt
- tests/test_request.py
- tox.ini
- webob/request.py
This fixes PATH_SAFE to include more of the safe characters from RFC3986.
Closes #290
> Fixup: PATH_SAFE

- tests/test_response.py
- webob/response.py
This fixes the bug reported by @dobesv in #254. Also documents that `expires` should not be a localtime, and that it should not be set in the past.
> Bugfix: set_cookie datetime

- tests/test_compat.py
- webob/compat.py
This supersedes PR #281.
This fixes Python bug https://bugs.python.org/issue27777
Closes #280, #281
> Bugfix: cgi FieldStorage

- docs/index.txt
- tests/test_response.py
- webob/response.py
This rips the band-aid off from the whole content-type parameters, and always removes them.
@mmerickel approved.
> Feature: remove ctype params

- tests/test_request.py
- webob/request.py
Resolves #88
I modified @bukzor's example slightly so it would round trip through webob's parsing
> Allow unnamed fields in form content

- tests/test_static.py
- webob/static.py
This fix prevents the static.DirectoryApp from leaking that a file exists
outside of the given path by first checking if the path is correct
before testing if the file exists.
> Prevent leaking if file exists outside of static path

- src/webob/cookies.py
When running Python 3 with the `-b` option, calling str() on a bytes instance raises a warning. This came up for us when running code with `-bb` enabled (which frequently helps catch bugs).
> Fix BytesWarning in webob.cookies._value_quote

- CHANGES.txt
- src/webob/acceptparse.py
- src/webob/request.py
Having ``request.accept_encoding`` return an ``Accept`` class was
strange and confusing, but more importantly the header needs its own
class for ``Accept-Encoding``-specific functionality. (See
https://github.com/Pylons/webob/issues/325)
Thanks!
> Change AcceptClass of request.accept_encoding to AcceptEncoding.

- docs/api/webob.txt
- src/webob/acceptparse.py
This is far from complete as documentation for the acceptparse.py classes, but as a lot may change in the near future, this pull request is mainly to set out the classes that need to be documented &mdash; I'll be changing and adding to this over the summer.
I added a comment about running into bugs with `:members` and `:inherited-members`, so that we remember why we chose to use `automethod` and `autoattribute` instead; and gave the comment a date so we can come back to it at a later date perhaps to check if the bugs have been fixed. Hope that's okay.
> Document acceptparse classes

- src/webob/acceptparse.py
- tests/test_acceptparse.py
Decided to leave documenting `.parsed` for later, because
1) Sphinx's `autoattribute` doesn't appear to work with instance variables created in `__init__()` when `__init__()` is inherited. I could get around it by making a class variable (`parsed = None`) and documenting that, but as the Accept* classes will soon stop inheriting from `Accept` and have their own `__init__`, we should be able to do it then.
2) Looking at the RFC, `.parsed` may need to have a more complicated form than (value, qvalue) for e.g. `MIMEAccept`. So we'll document each class's `.parsed` as we finish work on the parsing.
The tests already cover the `.parsed` attribute for the four headers, and we'll be adding more tests for `.__init__()` and `.parse()` that will cover the `.parsed` attribute, so no additional tests …
> Expose ``Accept.parsed``.

- docs/api/webob.txt
`:members:` and `:inherited-members:` works well enough (see https://github.com/Pylons/webob/issues/323#issuecomment-310218957, and thanks to @stevepiercy for the check). Sorry about that!
> Document acceptparse.py using :members: and :inherited-members:.

- CHANGES.txt
- src/webob/request.py
- tests/test_request.py
> Bugfix: ipv6 host support

- docs/api/webob.txt
- docs/conf.py
- src/webob/acceptparse.py
- src/webob/request.py
- tests/test_acceptparse.py
- tests/test_request.py
Some remaining questions:
1. How would you like me to do the imports in the tests? I can switch to module scope or fixtures, if either is your preference. (Module scope does seem to produce quite a lot of noise when one import is broken though, especially with tox and coverage, and I don't think fixtures are being used for imports in any WebOb tests at the moment.)
2. Would you prefer I switch from test classes to test functions? I see benefits to using test classes (namespacing, so e.g. we wouldn't have to repeat the class name in every test function name, leaving more room to be more descriptive with the name of the test; classes can be folded in editors), but don't know the benefits of test functions over classes. Happy to learn, and switch if test functions are your preference.
3. The …
> Accept language wip

- CHANGES.txt
- src/webob/request.py
- tests/test_request.py
> request.POST now supports any requests with the appropriate Content-Type (#351)

- CHANGES.txt
- src/webob/acceptparse.py
- tests/test_acceptparse.py
This updates MIMEAccept to mimic old behaviour better so that downstream
projects are not as broken.
The goal is not to provide the exact same behaviour, and thus MIMEAccept
still uses the new Accept header parsing and matching, however it is
much closer to the old API because it no longer raises on an invalid
header vs what was shipped in WebOb 1.8.0.
> MIMEAccept mimics old behaviour better

- src/webob/cookies.py
- src/webob/response.py
- tests/test_cookies.py
Correctly coerce non-bytes to bytes when serializing `SameSite` so that it's use matches that of the other parameters allowed by `Response.set_cookie` and `cookies.make_cookie`.
Closes https://github.com/Pylons/webob/issues/361
Related https://github.com/Pylons/webob/pull/362
> Bugfix: non-bytes samesite

- CHANGES.txt
- src/webob/acceptparse.py
- tests/test_acceptparse.py
> do not raise on offers that do not match the media type ABNF

- src/webob/compat.py
- src/webob/cookies.py
- src/webob/headers.py
- src/webob/multidict.py
- tests/test_request.py
`collections.MutableMapping` and other abc types were deprecated in 3.3 and will be removed in 3.8
> use collections.abc for abc types if available

- src/webob/acceptparse.py
This addresses https://github.com/Pylons/webob/issues/382: removes `asterisk_non0_found`, rearranges for readability, and removes an unnecessary blank line. Thanks!
> Remove asterisk_non0_found

- README.rst
The current travis-ci link in the README.rst links to `.org`. Since travis has migrated to `.com` this causes the image to break. This PR resolves this.
> Update travis link in README.rst

- src/webob/acceptparse.py
Just a small fix for the link to RFC 7231 in the MIMEAccept docstring (it was showing as `rfc:RFC 7231, section 5.3.2 <7231#section-5.3.2>` instead of `RFC 7231#section-5.3.2`), plus fix for a typo. Thanks!
> Fix link to RFC and typo.

- src/webob/cookies.py
- src/webob/response.py
- tests/test_cookies.py
https://github.com/Pylons/webob/issues/406
> Allows samesite='none' in set_cookie

- CHANGES.txt
- src/webob/cookies.py
- tests/test_cookies.py
PR #407 expanding the list of allowable SameSite values to included the string `"None"`.
This PR introduces a module flag `SAMESITE_VALIDATION` to bypass this check if/when the cookie specification or major browser implementations change again:
import webob.cookies
webob.cookies.SAMESITE_VALIDATION = False
ck = webob.cookies.make_cookie(cookie_name, value, samesite='future')
> disable validating the SameSite value, if/when the cookie spec changes

- src/webob/request.py
- tests/test_request.py
Currently, request.POST reads from `wsgi.input` without rewinding the stream on a `webob._parsed_post_vars` cache miss. This means that WSGI middlewares using WebOb could incidentally prevent a downstream WSGI application from obtaining the raw request body if it uses a different framework.
Here, we seek the raw body file back to its start after cgi parses it.
I've included a test that captures the desired behavior, which fails without the new change. If this is an unreasonable use case or intentional behavior, I'd love to learn more about it. Thanks in advance.
> Rewind body_file_raw after parsing in POST

- CHANGES.txt
- src/webob/response.py
- tests/test_response.py
The `Response.body_file` is described as a file-like object. However, the `write` method does not return the wrote length.
> add return value to Response.write

- src/webob/response.py
- tests/test_response.py
[RFC7230](https://tools.ietf.org/html/rfc7230#section-4.2.2) specifies
that
>   The "deflate" coding is a "zlib" data format [RFC1950](https://tools.ietf.org/html/rfc1950) containing a
>   "deflate" compressed data stream [RFC1951](https://tools.ietf.org/html/rfc1951) that uses a combination of
>   the Lempel-Ziv (LZ77) compression algorithm and Huffman coding.
but also
>       Note: Some non-conformant implementations send the "deflate"
>       compressed data without the zlib wrapper.
Thus deflate coded data should be expected to be received within a
"zlib" container, however if no container is present, the data shouldn't
be rejected.
This patch tries to decode that data using RFC7230 conformant decoding
and falls back to unwrapped decoding only if the previous attempt didn't
work.
> deflate'd response: use RFC compliant decompression by default

- CHANGES.txt
- src/webob/response.py
- tests/test_response.py
This is a backport of #424 onto the 1.8-branch as suggested in #425 
[RFC7230](https://tools.ietf.org/html/rfc7230#section-4.2.2) specifies
that
>   The "deflate" coding is a "zlib" data format [RFC1950](https://tools.ietf.org/html/rfc1950) containing a
>   "deflate" compressed data stream [RFC1951](https://tools.ietf.org/html/rfc1951) that uses a combination of
>   the Lempel-Ziv (LZ77) compression algorithm and Huffman coding.
but also
>       Note: Some non-conformant implementations send the "deflate"
>       compressed data without the zlib wrapper.
Thus deflate coded data should be expected to be received within a
"zlib" container, however if no container is present, the data shouldn't
be rejected.
This patch tries to decode that data using RFC7230 conformant decoding
and falls back …
> backport of #424 (was: deflate'd response: use RFC compliant decompression by default)

- docs/wiki-example-code/example.py
- src/webob/acceptparse.py
- src/webob/cookies.py
- src/webob/exc.py
- src/webob/request.py
- tests/test_client.py
- tests/test_compat.py
- tests/test_dec.py
- tests/test_multidict.py
- tests/test_response.py
- tests/test_static.py
- tests/test_util.py
> Convert from unittest.TestCase to py.test

- setup.py
Backport of #467
Unfortunate 1.8 is significantly behind the main branch re CI:  Latest tested version is Python 3.7 (!!) and there's no Github Actions.  Doesn't seem much point trying to backport that so I didn't bother.  I did however confirm tests do pass in Python 3.13.
[tox-py313.txt](https://github.com/user-attachments/files/17337305/tox-py313.txt)
> Backport `legacy-cgi` to 1.8 branch

- .coveragerc
- contributing.md
- setup.cfg
- Remove Python 2.x instructions
- Use correct modern targets
- record test contexts to output, refs: https://pytest-cov.readthedocs.io/en/stable/contexts.html
> docs,tests: update contributing running tests section
